### ISSUE TITLE
Not working for new worker site

### ISSUE THREAD

**Issue by c2c533c4f237** [Anveio/mturk-engine#10]
# Issue summary

When I go to the https://www.mturk.com/mturk/findhits?mturkengine , I am redirected to a new worker page that the script does not run on, https://worker.mturk.com/projects?ref=w_fr_srch . In addition if I manually change the script to force it to run on https://www.mturk.com/mturk/findhits?mturkengine&doNotRedirect=true , I still get errors "the search returned no results" so it just needs to be updated across the board.

## Expected behavior

Script needs to be updated since the worker site is redirecting the previous url and that the other worker site changes did not break this.

## Actual behavior

Page redirects, and when forced not to redirect can't return results. Everything needs to be updated for the new worker site.

## Steps to Reproduce the Problem

1. Load script
2. Go to URL
3. Be redirected to a different page

**Comment by Anveio** [comment]
Hi @c2c533c4f237 thanks for submitting this issue. The 1.4.0 update will have full compatibility with the worker site and should be out in a few days.

**Comment by Anveio** [comment]
Update's out. And the script should now work on https://worker.mturk.com?mturkengine 

Closing this issue for now. Feel free to open specific issues for bugs in the new update.
