### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ddrtn365WW** [Anveio/mturk-engine#11]
Thank you for creating this.  Could you include the Requester name in the area with the details so it can be copied.  I use it to cross reference my completed hits and am unable to highlight and copy from the main entry.  I know I can copy to clipboard, but that creates a lot of effort to acquire the requester name in my paste.  See sample below:

Requester:  Insert this line

Description: ---

Time allotted: ---

If you can't, that's OK, but it would be very helpful.

Thanks

**Comment by Anveio** [comment]
Sure that sounds very doable. I wasn't even aware it's not possible to highlight requester's names, thanks for letting me know! I'll include this with the next minor release, which should be within the next few days.

**Comment by ddrtn365WW** [comment]
Thanks, I appreciate it.

**Comment by Anveio** [comment]
Added in 1.4.2: https://github.com/Anveio/mturk-engine/releases/tag/1.4.2 although I'd like to get requester names highlightable ASAP.

**Comment by ddrtn365WW** [comment]
That will help very much, thanks!
