### ISSUE TITLE
Only Displays First 20 HITs on Account Page

### ISSUE THREAD

**Issue by dlj66** [Anveio/mturk-engine#13]
# Issue summary

Only the first twenty HITs are displayed on the Accounts page under the selected date.

## Expected behavior

On 1/16/18 I did 23 HITs. It's only showing 20. I verified the 23 HITs on the MTurk dashboard.

## Actual behavior

I expected it to show all 23 HITs

## Steps to Reproduce the Problem

1. Perform more than 20 HITs through MTurk
2. Go into Account tab
3. Select box with date in question. All HITs not listed. 

## Specifications

- Mturk Engine version: Most recent version (downloaded it 4 days ago)
- Are you using the Lite version?  Yes
- Browser: Google Chrome

**Comment by Anveio** [comment]
Hi @dlj66 thanks for submitting this issue. I have what I believe to be a fix for this ready but I'll need to find time to do enough HITs in a single day to thoroughly test it. Once I've done that (hopefully in the next few days) I'll update Mturk Engine with the fix.

**Comment by Anveio** [comment]
This should be fixed in 1.4.4, specific commit: https://github.com/Anveio/mturk-engine/commit/fbd4a46a6a6d92220962bf147942762effb4422c

Feel free to click the "Reopen Issue" button or post a new issue if the problem still occurs after updating.
