### ISSUE TITLE
Buttons don't update on line changes

### ISSUE THREAD

**Issue by Omniphantasm** [Anveio/mturk-engine#14]
# Issue summary

When the lines shift you've got to move mouse off of a segment and back onto it to expose the add/hide/mark as viewed buttons.

## Expected behavior

When a line shifts the relevant options should still display instead of having to move on and off to see them.

## Actual behavior
Buttons don't appear.

## Steps to Reproduce the Problem

1. Put mouse over "hide" and click
2. Try to click hide again for the next hit on the list.
3. Move mouse off of the line and back onto it

## Specifications

- Mturk Engine version:  1.4.3
- Are you using the Lite version? No
- Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by Anveio** [comment]
Hi @Omniphantasm thanks for submitting this issue. I might not be able to fix this as I rely on a component library for search results/queue/blocked hits/submitted hits. 

The display of the action buttons is controlled by internal state  [https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/Item.tsx#L197-L204](that's toggled with mouse enter and mouse leave). 

That particular component is getting a major overhaul soon which hopefully will support the action buttons displaying when an item in the list is removed but most likely I'll have to rethink how hiding multiple HITs in succession would work.

**Comment by Anveio** [comment]
This issue should be fixed as of 1.8.0. Feel free to re-open this issue if it persists after updating.
