### ISSUE TITLE
Unable to copy and paste the Requester and HIT names

### ISSUE THREAD

**Issue by awoegno** [Anveio/mturk-engine#17]
One more question:

Some areas of the script do not allow me to highlight the text so it can be copied. On the Search and Queue pages, I would like to be able to highlight the Requester name and the HIT name so I can copy it, but it doesn't highlight. How do I do this?

Thanks!

Specifications

Mturk Engine version: 1.4.4
Are you using the Lite version? Mturk Engine (Lite)
Browser: Chrome

**Comment by awoegno** [comment]
I think I just got this to work. If I place the mouse slightly above and to the left of what I want to highlight, it will select it. But it selects the whole line instead of just the words I want. If you can  fix this great, but if it is too much work, that is fine. I can just use this little workaround.

**Comment by Anveio** [comment]
This sounds similar to https://github.com/Anveio/mturk-engine/issues/11 . You can copy the requester name after expanding a search result but that and all the other work arounds are obviously not ideal. The company that produces the fantastic component library I'm using for displaying search results, queue items, and submitted HITs is releasing a major overhaul to that particular component soon so fingers are crossed that highlighting won't be an issue after the update.

**Comment by Anveio** [comment]
v1.7.0 removed the requester name from the collapsible section of a search result, but the button now has a first class way of copying parts of the requester's information. 

![image](https://user-images.githubusercontent.com/8881711/39624885-f7acf19a-4f68-11e8-8a7d-1f63350a3994.png)


Feel free to open another issue if you have ideas to improve this feature further.
