### ISSUE TITLE
Issue updating "Tracker Overview" after the last update

### ISSUE THREAD

**Issue by balder85** [Anveio/mturk-engine#20]
# Issue summary

Hi there, after the latest update that I installed just today, I'm unable to update the "Tracker Overview" overview
## Expected behavior

Today after your last push-update

## Actual behavior

The sync option seems to be brocken

## Steps to Reproduce the Problem

1. 2. 3.

## Specifications

* Mturk Engine version: latest update Mturk Suite v2.1.13
* Browser: Chrome 64x

**Comment by Anveio** [comment]
Hi @balder85 thanks for posting this issue. I'm a little confused, though, by what you mean. There's no "Tracker Overview" in Mturk Engine and I haven't released an update today.

It seems you meant to post an issue for Mturk Suite, which is a separate project that I'm not involved with. You can find the issues page for Mturk Suite here: https://github.com/Kadauchi/mturk-suite/issues

**Comment by balder85** [comment]
Thank you for reaching me, what I mean is when I try to sync option, data doesn't seems to be update, I tried to reinstall the extention, but en vain, and even worse, I couldn't even import my backup dbase. Here is a screenshoot of what's look like : 
https://imgur.com/a/hlqfE

Thank you in advance!

**Comment by balder85** [comment]
@Anveio 
Thank you for reaching me, what I mean is when I try to sync option, data doesn't seems to be update, I tried to reinstall the extention, but en vain, and even worse, I couldn't even import my backup dbase. Here is a screenshoot of what's look like :
https://imgur.com/a/hlqfE

Thank you in advance!
