### ISSUE TITLE
Suggestion: Add the HIT ID and Requestor Name+ID to the watcher

### ISSUE THREAD

**Issue by aesha-CORUS** [Anveio/mturk-engine#22]
# Issue summary

Please Add the HIT ID and Requestor Name+ID to the watcher

**Comment by Anveio** [comment]
Thanks for posting this suggestion @aesha-CORUS. You can get the HIT ID from the "Copy ID" button on each watcher. Would you rather it be visible at all times? I like the idea to have requester names and IDs available on each watcher but I'm not sure about adding another card to the watcher UI. I might make the "Add as Watcher" button add the requester name and ID to the description by default.

**Comment by aesha-CORUS** [comment]
It would be very nice to have the requester name visible, with the "Copy
ID"  link next to it to make it more visible. I totally missed it! Sorry
about that :(

That would just be adding text, much as you described, by passing it from
the "Add as Watcher" button.

One other question for you. How deep does the search go? Hit tracker from
the Mturk suite has a max of 100 before it breaks and returns nothing, but
yours doesn't say, nor have I found a way to configure it.

Thanks so much for your reply, I love your program, and use it daily.

Chloe (@aesha-CORUS)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Anveio** [comment]
I think I'll add that functionality to the Add as Watcher button then.

Mturk Engine requests 100 results, which is the maximum, by default. I chose not to have that be a configurable option early on because displaying a large number of results shouldn't present a performance problem (hopefully) and attempting to request more can break things, which can be confusing, especially for people who aren't aware of the built-in limit.

**Comment by aesha-CORUS** [comment]
Gotcha, thanks for the info, and the upcoming update!

**Comment by neocryptek** [comment]
You could add another link next to "Copy ID" for copying the requester ID (ex: two links: "Copy HID", "Copy RID" etc). That way it's not cluttering up the UI too much (ex: another card or always visible in description).

**Comment by Anveio** [comment]
This feature landed in v1.7.0. Feel free to open another issue if you run into a bug or if you have ideas to improve it further.
