### ISSUE TITLE
Feature Request: Audio Sounds/Notifications Only For Queue Changes

### ISSUE THREAD

**Issue by neocryptek** [Anveio/mturk-engine#26]
# Issue summary

It would be nice if there was a setting to enable audio/notifications only for Queue changes by watchers (ex: not for search changes). The current settings seem to be all or nothing master switch?

## Expected behavior

I would like to have audio sound and/or notification only when a watcher adds something to my Queue. I don't want audio/notification when search results change. This way I can have watchers running in the background and be alerted when they pick something up.

Perhaps a checkbox under each audio/notification setting section to enable Queue-only audio/notifications?

## Actual behavior

The current audio/notifications are master on/off switches and don't have control over what can make a sound/notification.

## Steps to Reproduce the Problem

View settings tab, notice that audio/notifications are master on/off switches.

## Specifications

* Mturk Engine version: 1.6.2 (installed from GitHub)
* Browser: Firefox 59.0.2 (64-bit) (MacOS 10.11.6)

**Comment by Anveio** [comment]
Thanks for this suggestion @neocryptek. If I'm understanding you correctly, since the only other source of audio is from new search results, you want a way to toggle off just the audio that plays when a new search result is found? If so, I like that idea a lot and I'll try to ship it in 1.7.0.

**Comment by neocryptek** [comment]
Yeah; sounds good! Thanks!

**Comment by Anveio** [comment]
Muting the search tab landed in v1.7.0. If I add a feature to dispatch desktop notifications from somewhere other than the search tab I'll consider a way to disable notifications from search tab specifically as well.

Feel free to open a separate issue if you find a bug.
