### ISSUE TITLE
Add search to account page

### ISSUE THREAD

**Issue by aesha-CORUS** [Anveio/mturk-engine#32]
# Issue summary

On the account page, I would like to be able to search by requester name/ID/Hit name.
The ability to add a bonus (whose amount you dont know until its paid) would be enhanced by this.

**Comment by Anveio** [comment]
Thanks for this suggestion @aesha-CORUS, this is something I'm working on for the next major version.

**Comment by Anveio** [comment]
This feature was added in the 1.8.0 update. Feel free to open another issue if you have further suggestions.
