### ISSUE TITLE
Ability to copy HIT name

### ISSUE THREAD

**Issue by aesha-CORUS** [Anveio/mturk-engine#34]
**Ability to copy HIT name (Search/Queue/and especially Account)**

Add a button like the others to copy this?  That might work until/if the API updates)

I actually had to use the Markdown, put it in notepad, and grab it from there. Even that doesnt work when I have already hidden the HIT. Having to unblock/copy/[aste to notepad/reblock in a nuisance.

All to get the HIT name for an email request for more information. (Also useful to TO1)

**Comment by Anveio** [comment]
Thanks for the suggestion @aesha-CORUS. I should be able to fit this into the next minor version, which I'll release within the next few days.

**Comment by aesha-CORUS** [comment]
Thanks!

**Comment by Anveio** [comment]
This just landed in 1.7.2 https://github.com/Anveio/mturk-engine/releases/tag/v1.7.2
