### ISSUE TITLE
From QUEUE page, attempts to contact requester fail on Submit.

### ISSUE THREAD

**Issue by aesha-CORUS** [Anveio/mturk-engine#35]
# Issue summary

From QUEUE page, attempts to contact requester fail on Submit. (havent tested the other pages since your recent update)

Malformed message
Your message subject or body is missing or exceeds the maximum length. Please revise and try submitting your message again.

## Expected behavior

Well.. it should say the request was successful, and send me to Mturks HIT page.

## Actual behavior

**Error Message:**
Malformed message
Your message subject or body is missing or exceeds the maximum length. Please revise and try submitting your message again.
[http://prntscr.com/je45tr](url)

I contacted Amazon about this before, and after 2 weeks said they had researched it, and that Mturk Engine was the cause. (I can contact requester successfully from normal Mturk pages)
[http://prntscr.com/je46tq](url)

## Steps to Reproduce the Problem
1. Have a HIT in queue
2. Try to contact requester from the drop down menu
3. Type in a short test message
4. Submit

## Specifications

* Mturk Engine version: 1.7.0
* Browser: Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by aesha-CORUS** [comment]
Some additional info. Here are the two URLs generated by Mturk, and Mturk Engine, for the same requester and HIT and the QUEUE:

**Yours:**
https://worker.mturk.com/contact_requester/assignment_messages/new?assignment_id=3E1QT0TDFP9GLW3VZML6OS6G066I8T&hit_type_message%5Bhit_description%5D=Investigate%20what%20is%20happening%20in%20the%20video%20from%20the%20beginning%20to%20the%20end%2C%20ear%20up%20to%20%240.75%20when%20you%20complete%20the%20HIT&hit_type_message%5Bhit_title%5D=Chat%20about%20what%20is%20happening%20in%20the%20video.%20%2A%2A%20Earn%20up%20to%20%240.75%20per%20HIT%20%2A%2A&hit_type_message%5Bhit_type_id%5D=32RJU5X1ZP9V6DK4741DB803V5RVD2&hit_type_message%5Brequester_id%5D=A1CEBF7WRZ74YK&hit_type_message%5Brequester_name%5D=Research%20Tasks&hit_type_message%5Bsubject%5D=Regarding%20Amazon%20Mechanical%20Turk%20Project%20%28HIT%20Type%29%2032RJU5X1ZP9V6DK4741DB803V5RVD2



**Mturks:**
https://worker.mturk.com/contact_requester/assignment_messages/new?assignment_message%5Bassignment_id%5D=3VSOLARPKB919Y4MJBKXKIZ20Z393U&assignment_message%5Bsubject%5D=Regarding+Amazon+Mechanical+Turk+HIT+3UL5XDRDNCJ1MOAM2ZXABZ6N2KU85Q&completed_date=2018-04-26&hit_id=3UL5XDRDNCJ1MOAM2ZXABZ6N2KU85Q&requester_id=A1CEBF7WRZ74YK&requester_name=Research+Tasks&title=Chat+about+what+is+happening+in+the+video.+%2A%2A+Earn+up+to+%240.75+per+HIT+%2A%2A

On the ACCOUNT page, when I lookup a completed HIT, the format is more in line with Mturks.

There are times I really **want** to complain to a requester about his HIT time lengths, broken content, or other things from the Queue (before it refreshes and disappears)

**Comment by Anveio** [comment]
This fix just shipped with 1.8.0. Feel free to reopen this issue if it persists after updating.
