### ISSUE TITLE
Suggestion - Ability to easily move watchers between folders

### ISSUE THREAD

**Issue by aesha-CORUS** [Anveio/mturk-engine#37]
**Ability to easily move watchers between folders**

WATCH LIST
Maybe a move button that gives you a folder dropdown list?

I run into HIT that I have in my watcher that I want to save, but not all the info I need to manually copy it to another folder is visible, nor is the option to manually create a new watcher available (another thing I would like), so a move option would be very handy!

**Comment by Anveio** [comment]
If I'm understanding you correctly, this feature actually exists. Under the settings section of any watcher, there should be a drop down under "Assigned folder" which has a list of all your folders. Select any of them to move the watcher to another folder.

Feel free to reopen this issue if that's not what you meant.
