### ISSUE TITLE
Can only set 2-3 Watchers at a time at no less than 5 seconds each

### ISSUE THREAD

**Issue by macheesmocat** [Anveio/mturk-engine#38]
# Issue summary

Watchers: 
I can only run 2 watchers at a time with a 3-5 second setting before I get a pop up error message: 

**Watcher titled "Social and Political Psychological Attitudes(~ 20 minutes)" has sent too many requests to MTurk and has been automatically stopped."**

## Expected behavior

I have not had any problem setting up to 20 watchers at 1 second attempts prior to Saturday May 5th, 2018. I have been using this fabulous mturk-engine for the past 2 months and have had nothing short of a great experience, no glitches or problems, thank you so much for your hard work! I love that it is so easy to use.

## Actual behavior
I am no longer able to set multiple watchers, (more than 2-3), not even for more than 5 second attempts each.

**Error message:
userscript.html?id=85c9f168-41ab-4d54-b49f-c3e337af8fe1:24 GET https://worker.mturk.com/projects/3ZA8T98ZC60I7Q6RPJTBL6SWAYQTFO/tasks/accept_random?format=gibberish 404 (Not Found)**

## Steps to Reproduce the Problem

I can reproduce the problem simply by setting more than 4 watchers at 3-5 second "time between attempts"

## Specifications

* Mturk Engine version: 1.7.1
* Browser: Google Chrome

**Comment by Anveio** [comment]
This seems similar to https://github.com/Anveio/mturk-engine/issues/31. If you've made too many requests to MTurk within a short amount of time, MTurk will temporarily block you from making more requests. The 1.7.0 update changed watchers to automatically cancel themselves when MTurk does this.

I agree that it seems like unexpected behavior, especially when this was happening prior to 1.7.0, albeit silently (watchers would continue to run but you'd have no chance of catching a HIT). Maybe I need to clarify the wording used to explain why it's happening, or add an option to disable it entirely.
