### ISSUE TITLE
Queue Page - HIT Times Not Working

### ISSUE THREAD

**Issue by dlj66** [Anveio/mturk-engine#44]
# Issue summary

The remaining times for HITs on the Queue page are not working.

## Expected behavior

Previously, if you were on the Queue page, the HITs in your queue would show how much time was left and would "countdown" in real time. 

## Actual behavior

Now, the times are "frozen" and don't show currently how much time is left unless you manually refresh the queue.

## Steps to Reproduce the Problem

Just access queued HITs on Queue page.

## Specifications

* Mturk Engine version: 1.8.2
* Browser: Chrome 67.0.3396.87

**Comment by Anveio** [comment]
Thanks for posting this issue @dlj66 , I'll have a bugfix up soon. 

Looks like I left behind an unnecessary getDerivedStateFromProps function when upgrading to React 16.4.1. https://github.com/Anveio/mturk-engine/blob/master/src/components/QueueCard/QueueTimer.tsx#L23-L27

**Comment by Anveio** [comment]
Should be fixed as of 1.8.3 https://github.com/Anveio/mturk-engine/releases/tag/v1.8.3 also found another easy performance win in there.

**Comment by dlj66** [comment]
Awesome. I will download the update. Thanks.

Keep up the great work! MTurk Engine is awesome!
