### ISSUE TITLE
Can only see first 25 hits submitted.

### ISSUE THREAD

**Issue by gravnash** [Anveio/mturk-engine#5]
I was excited to see the update, but there seems to be a persistent bug under the HIT Database area.

Tried installing both the normal version and the lite version, on Chrome and on Firefox, uninstalling and reinstalling, disabling and then uninstalling all other Turk-related scripts. But no matter what changes I make, I still only see the first 25 submitted as shown in the attached photos--and as a result, obviously, my daily estimated total is way off. The number of hits submitted didn't even change after I found some through watchers, refreshed the database, and checked again. Still 25.

Any ideas on this one?
![screen shot 2017-10-12 at 5 27 25 pm](https://user-images.githubusercontent.com/19578769/31520077-a7f1f7ae-af72-11e7-8a1c-58cfc33e0bf9.png)
![screen shot 2017-10-12 at 5 27 12 pm](https://user-images.githubusercontent.com/19578769/31520078-a803fada-af72-11e7-9c6a-73f5644b1309.png)

**Comment by Anveio** [comment]
Hi @gravnash thanks for posting this issue. I'll look into it tomorrow and hopefully have a fix soon.

**Comment by Anveio** [comment]
This issue should be fixed in v1.3.1.

Specific commit:
https://github.com/Anveio/mturk-engine/commit/760ff7d9a18b543a31a40b7ceb3fa10bd8c26506

Let me know if you keep having issues after updating. Closing this for now.
