### ISSUE TITLE
audio notifications not working anymore

### ISSUE THREAD

**Issue by mikmik111** [Anveio/mturk-engine#59]
# Issue summary

Since yesterday, Audio for finding a new hit is not working, although everything else seems to be working properly.

## Expected behavior

When Search finds a new hit, an audio will play.

## Actual behavior

Search finds a new hit but there's no audio notification, even though it's globally enabled.

## Steps to Reproduce the Problem

1. Click Start Searching
2. Search finds a hit
3. You see the hit show up but no audio beep

## Specifications

* Mturk Engine version: 1.8.3
* Browser: Opera (tried it on chrome as well, same issue)

**Comment by mikmik111** [comment]
I found out what the issue was, I don't know if it is just me, but the site where the audio was stored, (kiwi6.com) doesn't work and has issues downloading the audio file.

**Comment by Anveio** [comment]
Thanks for reporting this issue @mikmik111 I'll look into a fix and release a version of the app with a fix soon.

**Comment by mikmik111** [comment]
thanks for your hard work on this!

**Comment by Anveio** [comment]
Should be resolved!
