### ISSUE TITLE
Mturk engine Audio sound is not working, since 1 week ago, please solve the issue

### ISSUE THREAD

**Issue by shamshattar** [Anveio/mturk-engine#60]
# Issue summary

Thanks for submitting an issue to Mturk Engine. Use this space to provide a high-level summary of the problem or feature request:

## Expected behavior

When the problem occurs, what do you think should have happened? If the issue is a feature request, what would you like to see?

## Actual behavior

What actually happened? Include any error messages you see in the console when the issue occurs (press F12 while using Mturk Engine to see the console).

## Steps to Reproduce the Problem

1. 2. 3.

## Specifications

* Mturk Engine version:
* Browser:

**Comment by Anveio** [comment]
Sorry it took so long to get around to this @shamshattar but the problem should be fixed now. It was an issue with the platform that hosts the sound files. Closing for now, let me know if the issue reoccurs.
