### ISSUE TITLE
Audio is not working please we are in very trouble please sort out the issues

### ISSUE THREAD

**Issue by shamshattar** [Anveio/mturk-engine#61]
# Issue summary

Thanks for submitting an issue to Mturk Engine. Use this space to provide a high-level summary of the problem or feature request:

## Expected behavior

When the problem occurs, what do you think should have happened? If the issue is a feature request, what would you like to see?

## Actual behavior

What actually happened? Include any error messages you see in the console when the issue occurs (press F12 while using Mturk Engine to see the console).

## Steps to Reproduce the Problem

1. 2. 3.

## Specifications

* Mturk Engine version:
* Browser:

**Comment by Anveio** [comment]
Resolved, fortunately. See https://github.com/Anveio/mturk-engine/issues/60

**Comment by shamshattar** [comment]
thanks Anveio/mturk-engine
